// This file is generated by Slice Machine. Update with care!

import Grid from './Grid';
import RichText from './RichText';

export {
	Grid,
	RichText,
};

export const components = {
	grid: Grid,
	rich_text: RichText,
};
